### ISSUE TITLE
failed to connect existing session

### ISSUE THREAD

**Issue by tnakazato** [idia-astro/carta-python#27] opened 2021-10-28 00:44 UTC
Failed to connect existing backend server from carta-python. I first launched carta headless (no HTTP) backend with recommended grpc port.

```
$ carta --no_browser --no_http --grpc_port 50051
touch: cannot touch ‘/remote/home/nakazato/.local/share/icons/hicolor/.xdg-icon-resource-dummy’: No such file or directory
[2021-10-25 08:46:50.136] [info] Writing to the log file: /remote/home/nakazato/.carta/log/carta.log
[2021-10-25 08:46:50.137] [info] /tmp/.mount_cartaktBuPR/bin/carta_backend: Version 2.0.0
[2021-10-25 08:46:50.154] [info] CARTA gRPC service available at 0.0.0.0:50051
[2021-10-25 08:46:50.155] [info] Listening on port 3002 with top level folder /, starting folder /work/test/nakazato. The number of OpenMP worker threads will be handled automatically.
```

Then, I attempted to access the session from python but it failed.

```
>>> from carta.client import Session
>>> img1 = session.open_image('Ori-KL.spw0.cube.I.sd.fits')
...
carta.util.CartaActionFailed: CARTA scripting action fileBrowserStore.getFileList called with parameters [{"macroTarget": "fileBrowserStore", "macroVariable": "startingDirectory"}] failed: Invalid session ID 1.
```

I tried other session ID but didn't work. Strange thing is that, although gRPC security token will be displayed according to the [documentation](https://carta-python.readthedocs.io/en/latest/quickstart.html#connecting-to-an-existing-session), I didn't see such information on the terminal when I launched the backend.

**Comment by confluence** [comment] 2021-10-28 11:39
The version of CARTA you are using is too old. The current scripting wrapper only works with the 3.0 beta version of the package. This is available as an alternative to the 2.0 release version.

**Comment by tnakazato** [comment] 2021-10-28 23:32
Thanks. Since I installed multiple versions, I might mixed up the version. I will try again with the correct version.

**Comment by tnakazato** [comment] 2021-10-29 04:49
I tried again with the correct version of CARTA (3.0.0-beta1b). But I still see the error.

```
[nakazato@ana05]$ ls -l ~/carta/current/carta 
lrwxrwxrwx. 1 nakazato almacomp 54 Oct 29 13:34 /remote/home/nakazato/carta/current/carta -> ../3.0.0-beta.1b/CARTA-v3.0.0-beta.1b-redhat7.AppImage
[nakazato@ana05] $ carta --no_browser --no_http --grpc_port 50051
touch: cannot touch ‘/remote/home/nakazato/.local/share/icons/hicolor/.xdg-icon-resource-dummy’: No such file or directory
[2021-10-29 13:36:06.951] [info] Writing to the log file: /remote/home/nakazato/.carta-beta/log/carta.log
[2021-10-29 13:36:06.952] [info] /tmp/.mount_cartaTr5u8p/bin/carta_backend: Version 3.0.0-beta.1b
[2021-10-29 13:36:06.971] [info] CARTA gRPC service available at 0.0.0.0:50051
[2021-10-29 13:36:06.971] [info] CARTA gRPC token: 4411ef26-9ad0-44bd-9dde-7f1960365328
[2021-10-29 13:36:06.973] [info] Listening on port 3002 with top level folder /, starting folder /work/test/nakazato/casa. The number of OpenMP worker threads will be handled automatically.
```

Session seems to run. I got gRPC token now. So I used it to connect from Python. The error is as follows. Error message looks the same as before, which is "Invalid session ID".

```
(carta-cli) [nakazato@ana05 carta_test]$ python3
Python 3.6.12 (default, Oct 23 2020, 13:36:31) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from carta.client import Session
>>> session = Session.interact('localhost', 50051, 1, '4411ef26-9ad0-44bd-9dde-7f1960365328')
>>> img1 = session.open_image('Ori-KL.spw0.cube.I.sd.fits')
Traceback (most recent call last):
  File "/remote/home/nakazato/pyenv/carta-cli/lib64/python3.6/site-packages/carta/client.py", line 229, in call_action
    metadata=metadata
  File "/remote/home/nakazato/pyenv/carta-cli/lib64/python3.6/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/remote/home/nakazato/pyenv/carta-cli/lib64/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.OUT_OF_RANGE
	details = "Invalid session ID 1."
	debug_error_string = "{"created":"@1635482446.072639363","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Invalid session ID 1.","grpc_status":11}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/remote/home/nakazato/pyenv/carta-cli/lib64/python3.6/site-packages/carta/validation.py", line 522, in newfunc
    return func(self, *args, **kwargs)
  File "/remote/home/nakazato/pyenv/carta-cli/lib64/python3.6/site-packages/carta/client.py", line 371, in open_image
    return Image.new(self, path, hdu, False)
  File "/remote/home/nakazato/pyenv/carta-cli/lib64/python3.6/site-packages/carta/client.py", line 740, in new
    path = session.resolve_file_path(path)
  File "/remote/home/nakazato/pyenv/carta-cli/lib64/python3.6/site-packages/carta/client.py", line 292, in resolve_file_path
    return f"{self.pwd()}/{path}"
  File "/remote/home/nakazato/pyenv/carta-cli/lib64/python3.6/site-packages/carta/client.py", line 303, in pwd
    self.call_action("fileBrowserStore.getFileList", Macro("fileBrowserStore", "startingDirectory"))
  File "/remote/home/nakazato/pyenv/carta-cli/lib64/python3.6/site-packages/carta/client.py", line 233, in call_action
    raise CartaActionFailed(f"{carta_action_description} failed: {e.details()}") from e
carta.util.CartaActionFailed: CARTA scripting action fileBrowserStore.getFileList called with parameters [{"macroTarget": "fileBrowserStore", "macroVariable": "startingDirectory"}] failed: Invalid session ID 1.
```

**Comment by confluence** [comment] 2021-10-29 06:34
OK, I see now that in the code snippet in your original report you didn't show how you created the `session` object. In the new snippet, you are using `interact`, but you are launching `carta` without a browser or HTTP server. `interact` is for interacting with an existing session which you already have open in a browser. You would get the ID from the browser. There is no session with ID 1.

If you want to use `interact`, you first need to open an interactive session in CARTA as normal. If you want to use CARTA headlessly, you need to use `connect` or `new` (make sure that you have the additional optional dependencies installed). If you use `connect` (to connect to a backend you started yourself), use `--no_browser`, but *not* `--no_http`.

**Comment by tnakazato** [comment] 2021-10-29 07:49
Thanks. With `connect`, it seems I established the session. However, I got an error when I tried to open image. FYI, I launched CARTA backend on a remote server and connected from my laptop PC. I tried to open both images located in local and remote disk. But neither images worked. Here is an error.

```
---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
~/pyenv/carta-cli/lib/python3.9/site-packages/carta/client.py in call_action(self, path, *args, **kwargs)
    226                 stub = carta_service_pb2_grpc.CartaBackendStub(channel)
--> 227                 response = stub.CallAction(
    228                     request=carta_service_pb2.ActionRequest(**request_kwargs),

~/pyenv/carta-cli/lib/python3.9/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    945                                       wait_for_ready, compression)
--> 946         return _end_unary_response_blocking(state, call, False, None)
    947 

~/pyenv/carta-cli/lib/python3.9/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    848     else:
--> 849         raise _InactiveRpcError(state)
    850 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "failed to connect to all addresses" 
    debug_error_string = "{"created":"@1635492749.390580000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1635492749.390579000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}" 
>

The above exception was the direct cause of the following exception:

CartaActionFailed                         Traceback (most recent call last)
<ipython-input-16-ed8fd86418b3> in <module>
----> 1 img1 = session.open_image(imagename)
...
```

**Comment by confluence** [comment] 2021-10-29 08:09
Please provide the full Python code snippet that you are using to create the session and open the images.

You can only open images that are available to the backend on the remote server (but that's not the issue here, otherwise you would be seeing errors about the images not existing). It looks like you are not connecting to the remote backend correctly, so I think the problem must be in the line where you create the session. Are you specifying a remote host?

**Comment by tnakazato** [comment] 2021-11-04 02:43
Here is what I did. I did port forwarding so that I can access CARTA backend through localhost.

## backend (remote server)
```
$ ls -l ~/carta/current/
total 0
lrwxrwxrwx. 1 nakazato almacomp 54 Oct 29 13:34 carta -> ../3.0.0-beta.1b/CARTA-v3.0.0-beta.1b-redhat7.AppImage
$ ~/carta/current/carta --no_browser --grpc_port 50051
```

## frontend (laptop PC)
```
# activate venv and launch ipython
$ source ~/pyenv/carta-cli/bin/activate
$ ipython
# and below is what I did on ipython session
In [1]: from carta.client import Session
In [2]: from carta.browser import ChromeHeadless
In [17]: session = Session.connect(ChromeHeadless(), 'http://localhost:3002/?token=<http token>', '<grpc token>')
# at this point, I got a message on the remote server that the connection was established
In [18]: img1 = session.open_image(imagename)
# and here I got the error previously reported
```

**Comment by confluence** [comment] 2021-11-04 07:06
I can see a typo: `---grpc_port 50051`. You have an extra hyphen.

Can you please also paste the full output of the `carta` command? This typo should have resulted in the backend aborting with an error message.

**Comment by tnakazato** [comment] 2021-11-04 07:59
I think I pasted wrong line. I definitely run carta with `--grpc_port 50051`. Below is an output from carta command (masked IP address).

```
touch: cannot touch ‘/remote/home/nakazato/.local/share/icons/hicolor/.xdg-icon-resource-dummy’: No such file or directory
[2021-10-29 15:59:07.381] [info] Writing to the log file: /remote/home/nakazato/.carta-beta/log/carta.log
[2021-10-29 15:59:07.381] [info] /tmp/.mount_carta8WXv6K/bin/carta_backend: Version 3.0.0-beta.1b
[2021-10-29 15:59:07.400] [info] CARTA gRPC service available at 0.0.0.0:50051
[2021-10-29 15:59:07.400] [info] CARTA gRPC token: 7fc2edaf-ca98-4f0d-88ed-f160b2ee2147
[2021-10-29 15:59:07.401] [info] Serving CARTA frontend from /tmp/.mount_carta8WXv6K/share/carta/frontend
[2021-10-29 15:59:07.402] [info] Listening on port 3002 with top level folder /, starting folder /work/test/nakazato. The number of OpenMP worker threads will be handled automatically.
[2021-10-29 15:59:07.402] [info] CARTA is accessible at http://XXX.XXX.XXX.XXX:3002/?token=a1ac1c43-10f9-4081-a376-4ff93b721b8a
```

Also, I got additional log message from carta when I created session instance on Python.

```
[2021-10-29 16:31:36.656] [info] Session 1 [127.0.0.1] Connected. Num sessions: 1
```

**Comment by confluence** [comment] 2021-11-04 08:02
Are you forwarding the gRPC port to localhost?

**Comment by tnakazato** [comment] 2021-11-04 08:08
I think so. But I'm not 100% confident although I'm sure I forwarded 3002. Do I need to forward both 3002 and 50051?

**Comment by confluence** [comment] 2021-11-04 08:09
Yes; they are two separate ports. You have to forward both of them.

**Comment by tnakazato** [comment] 2021-11-08 01:52
I finally succeeded to open image. I really appreciate your help! Although I only did very quick check for the image, scripting interface seemed to work as expected. But I have a few comments. 

1. I saved rendered view to PNG file. I found that the file is created in the frontend file system although I loaded the image from backend file system. This is OK but this kind of asymmetry is bit confusing. 
2. Strange behavior of `session.save_rendered_view`. 
    * Default background color (`None`) didn't work although it is interpreted as transparent according to the documentation. It failed with `ValueError: None is not an HTML color specification.`. 
    * Keyword argument didn't work. When I set `background_color='white'`, it failed with `KeyError: 'background_color'`. It only worked when I set background color as positional argument.
3. Opposite axis order. I found that `img.shape` is `[1, 4096, 40, 56]` while FITS header is as follows. Is this intentional?
    ```
    NAXIS   =                    4                                                  
    NAXIS1  =                   56                                                  
    NAXIS2  =                   40                                                   
    NAXIS3  =                 4096     
    NAXIS4  =                    1 
    ```

**Comment by confluence** [comment] 2021-11-08 06:42
Yay, I'm glad you got it to work!

1. The scripting interface is an interface to the frontend (using the backend as a proxy) -- it uses the backend and frontend together. The way that the Python wrapper connects to CARTA is probably about to change, and I think the new way will be much less confusing.
2. Hmm. Can you show a code snippet which reproduces these two issues? It's quite possible that this wasn't tested properly.
3. This is normal; axis order in numpy (and thus most Python scientific tools; see e.g. [astropy](https://docs.astropy.org/en/stable/visualization/wcsaxes/slicing_datacubes.html)) is reversed from the axis order in FITS.

**Comment by tnakazato** [comment] 2021-11-08 07:02
Thank you for your reply. I understand. I send you a code snippet for the second issue.

```
# open image
img1 = session.open_image('Ori-KL.spw0.cube.I.sd.fits')

# this is OK
session.save_rendered_view('Ori-KL.png', 'white')

# this caused ValueError
session.save_rendered_view('Ori-KL.png')

# this caused KeyError
session.save_rendered_view('Ori-KL.png', background_color='#ffffff')
```

**Comment by confluence** [comment] 2021-11-08 07:08
Thanks! What about the `None` error?

**Comment by confluence** [comment] 2021-11-08 07:12
Actually, don't worry; I can see what is causing the `None` error. I will open a new issue for this and close this one.

**Comment by tnakazato** [comment] 2021-11-08 07:16
Default value for `background_color` is `None`. So, the second example of `save_rendered_view` corresponds to `None` error.

**Comment by tnakazato** [comment] 2021-11-08 07:17
Thank you for opening another issue. We can close this one now.

**Comment by confluence** [comment] 2021-11-08 07:17
OK, I am closing this now -- the new issue is #29.

**Comment by tnakazato** [comment] 2021-11-08 07:17
Thanks!

**Closed as completed by confluence** 2021-11-08 07:17 UTC
