### ISSUE TITLE
domain localhost missing in Ubuntu Appimage

### ISSUE THREAD

**Issue by lh-astro** [idia-astro/carta-python#22] opened 2021-09-12 14:35 UTC
Missing "localhost" in  http://:3002/?token=<token>

Version:
https://github.com/CARTAvis/carta/releases/download/v3.0.0-beta.1b/CARTA-v3.0.0-beta.1b-ubuntu.tgz

Command:
`./CARTA-v3.0.0-beta.1b-ubuntu.AppImage`

Output:
`[2021-09-12 16:14:48.180] [info] CARTA is accessible at http://:3002/?token=<token>`

**Comment by confluence** [comment] 2021-09-12 16:54
This is not related to the wrapper; it's a backend issue. It's probably a duplicate of [this](https://github.com/CARTAvis/carta-backend/pull/890) -- are you running the backend on a machine which is offline?

**Comment by lh-astro** [comment] 2021-09-12 17:52
Oh right, thanks.

**Comment by confluence** [comment] 2021-09-14 11:34
We have checked the AppImage, and the custom script it uses to launch CARTA still contains the bug which was fixed in the default launcher script in that linked issue. If you use the Ubuntu packages from the PPA, you should not encounter this problem.

I am closing this issue here, as it is unrelated to the wrapper.

**Closed as completed by confluence** 2021-09-14 11:34 UTC
